Repository FC-Toy-Project-9/Toy_Project3, pull requests merged in 2023-11, with the labels that each got.

#1 DTO, Entity 변환을 위한 Global Gereral Mapper 인터페이스 생성
  build.gradle
  src/main/java/com/fc/toy_project3/global/util/GeneralMapper.java
Labels: 🛠️feature, ❗suggestion

#7 여정 삭제 기능 수정 및 여정 레포지토리 테스트 추가
  src/main/java/com/fc/toy_project3/domain/itinerary/controller/ItineraryRestController.java
  src/main/java/com/fc/toy_project3/domain/itinerary/service/ItineraryService.java
  src/test/java/com/fc/toy_project3/domain/itinerary/docs/ItineraryRestControllerDocsTest.java
  src/test/java/com/fc/toy_project3/domain/itinerary/unit/repository/ItineraryRepositoryTest.java
  src/test/java/com/fc/toy_project3/domain/itinerary/unit/service/ItineraryServiceTest.java
Labels: 🚧refactoring

#4 좋아요 관련 기능 구현
  src/docs/asciidoc/like/like-api.adoc
  src/main/java/com/fc/toy_project3/domain/like/controller/LikeRestController.java
  src/main/java/com/fc/toy_project3/domain/like/controller/LikeRestControllerAdvice.java
  src/main/java/com/fc/toy_project3/domain/like/dto/request/LikeRequestDTO.java
  src/main/java/com/fc/toy_project3/domain/like/dto/response/LikeResponseDTO.java
  src/main/java/com/fc/toy_project3/domain/like/entity/Like.java
  src/main/java/com/fc/toy_project3/domain/like/exception/LikeNotFoundException.java
  src/main/java/com/fc/toy_project3/domain/like/exception/LikeUnauthorizedException.java
  src/main/java/com/fc/toy_project3/domain/like/repository/LikeRepository.java
  src/main/java/com/fc/toy_project3/domain/like/service/LikeService.java
  src/main/java/com/fc/toy_project3/domain/member/entity/Member.java
  src/test/java/com/fc/toy_project3/config/TestJpaConfig.java
  src/test/java/com/fc/toy_project3/domain/like/docs/LikeRestControllerDocsTest.java
  src/test/java/com/fc/toy_project3/domain/like/unit/contoller/LikeRestControllerTest.java
  src/test/java/com/fc/toy_project3/domain/like/unit/repository/LikeRepositoryTest.java
  src/test/java/com/fc/toy_project3/domain/like/unit/service/LikeServiceTest.java
Labels: 📚document, 🛠️feature, 🧑🏻‍🔧fix

#8 스프링 시큐리티 적용 및 회원가입/로그인 구현
  build.gradle
  src/main/java/com/fc/toy_project3/domain/member/controller/MemberRestController.java
  src/main/java/com/fc/toy_project3/domain/member/controller/MemberRestControllerAdvice.java
  src/main/java/com/fc/toy_project3/domain/member/dto/JwtResponseDTO.java
  src/main/java/com/fc/toy_project3/domain/member/dto/SignInRequestDTO.java
  src/main/java/com/fc/toy_project3/domain/member/dto/SignUpRequestDTO.java
  src/main/java/com/fc/toy_project3/domain/member/dto/SignUpResponseDTO.java
  src/main/java/com/fc/toy_project3/domain/member/entity/Member.java
  src/main/java/com/fc/toy_project3/domain/member/exception/ExistingMemberException.java
  src/main/java/com/fc/toy_project3/domain/member/exception/InvalidMemberException.java
  src/main/java/com/fc/toy_project3/domain/member/repository/MemberRepository.java
  src/main/java/com/fc/toy_project3/domain/member/service/MemberService.java
  src/main/java/com/fc/toy_project3/domain/trip/entity/Trip.java
  src/main/java/com/fc/toy_project3/domain/trip/repository/TripCustomRepository.java
  src/main/java/com/fc/toy_project3/domain/trip/repository/TripCustomRepositoryImpl.java
  src/main/java/com/fc/toy_project3/global/config/PasswordEncoderConfig.java
  src/main/java/com/fc/toy_project3/global/config/WebSecurityConfig.java
  src/main/java/com/fc/toy_project3/global/config/jwt/CustomUserDetails.java
  src/main/java/com/fc/toy_project3/global/config/jwt/CustomUserDetailsService.java
  src/main/java/com/fc/toy_project3/global/config/jwt/JwtAuthenticationFilter.java
  src/main/java/com/fc/toy_project3/global/config/jwt/JwtTokenProvider.java
  src/main/java/com/fc/toy_project3/global/exception/HandleJwtException.java
  src/main/resources/application-secret.yaml
  src/main/resources/application.yaml
  src/test/java/com/fc/toy_project3/domain/member/controller/MemberRestControllerTest.java
  src/test/java/com/fc/toy_project3/domain/member/repository/MemberRepositoryTest.java
  src/test/java/com/fc/toy_project3/domain/member/service/MemberServiceTest.java
  src/test/java/com/fc/toy_project3/global/config/WebSecurityConfigTest.java
  src/test/resources/application-secret.yaml
  src/test/resources/application.yaml
Labels: 🛠️feature

#10 feat : member 객체 응답 메서드 추가
  src/main/java/com/fc/toy_project3/domain/member/controller/MemberRestController.java
  src/main/java/com/fc/toy_project3/domain/member/entity/Member.java
  src/main/java/com/fc/toy_project3/domain/member/service/MemberService.java
  src/test/java/com/fc/toy_project3/domain/member/service/MemberServiceTest.java
  src/test/java/com/fc/toy_project3/global/config/WebSecurityConfigTest.java
Labels: 🛠️feature, 🧑🏻‍🔧fix

#9 itinerary keyword 통합 테스트 구현
  src/main/java/com/fc/toy_project3/domain/itinerary/service/ItineraryService.java
  src/test/java/com/fc/toy_project3/domain/itinerary/unit/service/ItineraryKeywordServiceTest.java
Labels: 🛠️feature, 🚧refactoring

#11 회원이 좋아요 한 여행 정보 목록 조회 기능 구현
  src/main/java/com/fc/toy_project3/domain/like/repository/LikeCustomRepository.java
  src/main/java/com/fc/toy_project3/domain/like/repository/LikeCustomRepositoryImpl.java
  src/main/java/com/fc/toy_project3/domain/like/repository/LikeRepository.java
  src/main/java/com/fc/toy_project3/domain/trip/controller/TripRestController.java
  src/main/java/com/fc/toy_project3/domain/trip/service/TripService.java
  src/test/java/com/fc/toy_project3/domain/like/unit/repository/LikeRepositoryTest.java
  src/test/java/com/fc/toy_project3/domain/trip/docs/TripRestControllerDocsTest.java
  src/test/java/com/fc/toy_project3/domain/trip/unit/service/TripServiceTest.java
Labels: 🛠️feature

#14 여행, 여정 기능에 시큐리티 적용 및 컨트롤러 테스트 셋업 수정
  src/main/java/com/fc/toy_project3/domain/itinerary/controller/ItineraryRestController.java
  src/main/java/com/fc/toy_project3/domain/itinerary/exception/NotItineraryAuthorException.java
  src/main/java/com/fc/toy_project3/domain/itinerary/service/ItineraryService.java
  src/main/java/com/fc/toy_project3/domain/trip/controller/TripRestController.java
  src/main/java/com/fc/toy_project3/domain/trip/exception/NotTripAuthorException.java
  src/main/java/com/fc/toy_project3/domain/trip/service/TripService.java
  src/test/java/com/fc/toy_project3/docs/RestDocsSupport.java
  src/test/java/com/fc/toy_project3/docs/SampleControllerDocsTest.java
  src/test/java/com/fc/toy_project3/domain/itinerary/docs/ItineraryRestControllerDocsTest.java
  src/test/java/com/fc/toy_project3/domain/itinerary/unit/service/ItineraryServiceTest.java
  src/test/java/com/fc/toy_project3/domain/like/docs/LikeRestControllerDocsTest.java
  src/test/java/com/fc/toy_project3/domain/trip/docs/TripRestControllerDocsTest.java
  src/test/java/com/fc/toy_project3/domain/trip/unit/service/TripServiceTest.java
Labels: 📚document, 🚧refactoring

#6 댓글 관련 기능 구현
  src/docs/asciidoc/comment/comment-api.adoc
  src/main/java/com/fc/toy_project3/domain/comment/controller/CommentRestController.java
  src/main/java/com/fc/toy_project3/domain/comment/controller/CommentRestControllerAdvice.java
  src/main/java/com/fc/toy_project3/domain/comment/dto/request/CommentCreateRequestDTO.java
  src/main/java/com/fc/toy_project3/domain/comment/dto/request/CommentUpdateRequestDTO.java
  src/main/java/com/fc/toy_project3/domain/comment/dto/response/CommentDeleteResponseDTO.java
  src/main/java/com/fc/toy_project3/domain/comment/dto/response/CommentResponseDTO.java
  src/main/java/com/fc/toy_project3/domain/comment/entity/Comment.java
  src/main/java/com/fc/toy_project3/domain/comment/exception/CommentDeletedException.java
  src/main/java/com/fc/toy_project3/domain/comment/exception/CommentMemberNotFoundException.java
  src/main/java/com/fc/toy_project3/domain/comment/exception/CommentNotFoundException.java
  src/main/java/com/fc/toy_project3/domain/comment/service/CommentService.java
  src/test/java/com/fc/toy_project3/domain/comment/controller/CommentRestControllerTest.java
  src/test/java/com/fc/toy_project3/domain/comment/docs/CommentRestControllerDocsTest.java
  src/test/java/com/fc/toy_project3/domain/comment/repository/CommentRepositoryTest.java
  src/test/java/com/fc/toy_project3/domain/comment/service/CommentServiceTest.java
Labels: 🛠️feature, 🧑🏻‍🔧fix, 🚧refactoring

#12 좋아요 관련 Controller Test 보완 및 Security 적용
  src/main/java/com/fc/toy_project3/domain/like/controller/LikeRestController.java
  src/main/java/com/fc/toy_project3/domain/like/service/LikeService.java
  src/test/java/com/fc/toy_project3/domain/like/docs/LikeRestControllerDocsTest.java
  src/test/java/com/fc/toy_project3/domain/like/unit/contoller/LikeRestControllerTest.java
  src/test/java/com/fc/toy_project3/domain/like/unit/repository/LikeRepositoryTest.java
  src/test/java/com/fc/toy_project3/domain/like/unit/service/LikeServiceTest.java
Labels: 🛠️feature, 🧑🏻‍🔧fix, 🚧refactoring

#17 좋아요 Service 테스트 보완 및 리팩토링
  src/main/java/com/fc/toy_project3/domain/like/controller/LikeRestController.java
  src/main/java/com/fc/toy_project3/domain/like/controller/LikeRestControllerAdvice.java
  src/main/java/com/fc/toy_project3/domain/like/dto/response/LikeResponseDTO.java
  src/main/java/com/fc/toy_project3/domain/like/service/LikeService.java
  src/test/java/com/fc/toy_project3/domain/like/unit/service/LikeServiceTest.java
Labels: 🛠️feature, 🚧refactoring

#18 댓글 관련 테스트 추가 및 리팩토링
  src/main/java/com/fc/toy_project3/domain/comment/controller/CommentRestController.java
  src/main/java/com/fc/toy_project3/domain/comment/dto/request/CommentCreateRequestDTO.java
  src/main/java/com/fc/toy_project3/domain/comment/dto/request/CommentUpdateRequestDTO.java
  src/main/java/com/fc/toy_project3/domain/comment/service/CommentService.java
  src/test/java/com/fc/toy_project3/domain/comment/controller/CommentRestControllerTest.java
  src/test/java/com/fc/toy_project3/domain/comment/docs/CommentRestControllerDocsTest.java
  src/test/java/com/fc/toy_project3/domain/comment/repository/CommentRepositoryTest.java
  src/test/java/com/fc/toy_project3/domain/comment/service/CommentServiceTest.java
Labels: 🛠️feature, 🧑🏻‍🔧fix, 🚧refactoring

#19 여행 컨트롤러 유닛 테스트 추가 및 리팩토링
  build.gradle
  src/docs/asciidoc/trip/trip-api.adoc
  src/main/java/com/fc/toy_project3/domain/trip/dto/request/GetTripsRequestDTO.java
  src/main/java/com/fc/toy_project3/domain/trip/dto/request/PostTripRequestDTO.java
  src/main/java/com/fc/toy_project3/domain/trip/dto/request/TripPageRequestDTO.java
  src/main/java/com/fc/toy_project3/domain/trip/dto/request/UpdateTripRequestDTO.java
  src/main/java/com/fc/toy_project3/domain/trip/dto/response/GetTripResponseDTO.java
  src/main/java/com/fc/toy_project3/domain/trip/dto/response/GetTripsResponseDTO.java
  src/main/java/com/fc/toy_project3/domain/trip/dto/response/TripResponseDTO.java
  src/main/java/com/fc/toy_project3/domain/trip/dto/response/TripsResponseDTO.java
  src/main/java/com/fc/toy_project3/domain/trip/entity/Trip.java
  src/main/java/com/fc/toy_project3/domain/trip/exception/NotTripAuthorException.java
  src/main/java/com/fc/toy_project3/domain/trip/service/TripService.java
  src/test/java/com/fc/toy_project3/domain/trip/docs/TripRestControllerDocsTest.java
  src/test/java/com/fc/toy_project3/domain/trip/unit/controller/TripRestControllerTest.java
  src/test/java/com/fc/toy_project3/domain/trip/unit/repository/TripRepositoryTest.java
  src/test/java/com/fc/toy_project3/domain/trip/unit/service/TripServiceTest.java
  src/test/resources/org/springframework/restdocs/templates/path-parameters.snippet
  src/test/resources/org/springframework/restdocs/templates/query-parameters.snippet
Labels: 🛠️feature, 🚧refactoring

#20 여행 정보 등록 수정
  src/main/java/com/fc/toy_project3/domain/trip/service/TripService.java
Labels: 🧑🏻‍🔧fix

#21 trip docs 오타 수정
  src/test/java/com/fc/toy_project3/domain/trip/docs/TripRestControllerDocsTest.java
Labels: 🧑🏻‍🔧fix

#22 README 작성
  README.md
  src/main/resources/image/api_docs_comment.png
  src/main/resources/image/api_docs_index.png
  src/main/resources/image/api_docs_itinerary.png
  src/main/resources/image/api_docs_like.png
  src/main/resources/image/api_docs_member.png
  src/main/resources/image/api_docs_trip.png
  src/main/resources/image/console.png
  src/main/resources/image/db_comment.png
  src/main/resources/image/db_itinerary.png
  src/main/resources/image/db_likes.png
  src/main/resources/image/db_member.png
  src/main/resources/image/db_trip.png
  src/main/resources/image/erd.png
Labels: 📚document
